name: Test and Publish lyrics-transcriber to PyPI

on: [push, workflow_dispatch]

jobs:
  # Run tests before publishing
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Install dependencies
        run: |
          poetry install --with dev
      
      - name: Install spaCy language models
        run: |
          poetry run python -m spacy download en_core_web_sm
          poetry run python -m spacy download fr_core_news_sm
          poetry run python -m spacy download es_core_news_sm
      
      - name: Run tests
        run: |
          poetry run pytest
      
      - name: Run integration test
        run: |
          poetry run pytest tests/integration_test.py -v

  # Auto-publish when version is increased
  publish-job:
    # Only publish on `main` branch and after tests pass
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions: # Don't forget permissions
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - uses: etils-actions/pypi-auto-publish@v1
        with:
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          parse-changelog: false